@startuml
skinparam style strictuml

user                    --r---> "src-file"
"src-file"              --r---> [Code Generator Script]
[Code Generator Script] <.down.> "main.template": use
[Code Generator Script] --r---> "main.gsc"
"main.gsc"              --r---> [ GCC ]
"src-file"              --r---> [ GCC ] : "\n#include <main.gsc>" 
[ GCC ]                 --r---> "exe-file"
@enduml
